---
title: "My English Activity Log : MEAL"
author:
  - name: "Louanne Degallaix" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---

- Oct. 11th: This week, I watched three Jimmy Fallon's videos. The first one is an interview of Gad Elmaleh. I didn't know he was making shows in America. In the second one Jimmy Fallon makes jokes about political news, covid,... In the last one, he jokes about persons who cough in restaurant, parents who have to help their children with their virtual homework,...
It was the first time I watched such programs. That makes me laugh. 

----

- Oct. 15th : Saturday, I get in touch again with my friend Millya. I met her on holiday 3 years ago. She comes from Russia. She does not speak French and I don’t speak Russian, so we speak English. We don’t take enough news of each other because of the time difference but it is always a pleasure to speak with her. We can talk about everything: series, music, school, difference between Belgium and Russia, … 

---

- Oct. 24th : I started the third season of killing Eve yesterday. At the beginning I watched that series in French. When the second season came out, I could not wait, and I watched it in English. Now I prefer in English (with subtitles of course). 
 It is the story of an inspector (Eve) who makes a link between murders. The killer (Villanelle) is a psychopath. When Villanelle learns that Eve investigates, she begins to play with her. 
Very good series! I advise you to look at it!!!!

---

- Nov. 11 th: Yesterday I began to read the book “Where are the children?” from Mary Higgins Clark. It is an edition for English learner. The story is in English but some words are translated into French. It is more pleasant because I do not need to use a dictionary. 

---
